import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Unity, useUnityContext } from "react-unity-webgl";

const Home: NextPage = () => {
  const { unityProvider } = useUnityContext({
    loaderUrl: "assets/WebGL.loader.js",
    dataUrl: "assets/WebGL.data",
    frameworkUrl: "assets/WebGL.framework.js",
    codeUrl: "assets/WebGL.wasm",
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>Laser Defender</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={styles.main}>
        <Unity
          style={{
            height: "100vh",
            width: "100vh",
          }}
          unityProvider={unityProvider}
        />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
